# listOfProduct ==> products
{
  products{
    _id
    title
    refrenceImage
    stock_limite
		discount
    price
    main_price
  }
}

# listOfProductById  ===> productById(id:"6526f8c4418a47f9f7f8957a")
{
  productById(id:"6526f8c4418a47f9f7f8957a"){
    brand_Id{
      title
    }
    brand_productCat_Id{
      title
    }
    title
    en_title
    refrenceImage
    fileUrl
    text
    short_text
    tags
    producer
    stock_limite
    discount
    main_price
    price
    send_date
  }
}

# variationProduct ===>  variationProduct(proId:"6526314167967494f76bddcd")
{
  variationProduct(proId:"6526314167967494f76bddcd"){
    variation_Id{
      name
    }
    value
  }
}

# listOfProductByCategory ===>  listOfProductByCategory(catId:"65264def2b0b88ce46cc9f64")
{
  listOfProductByCategory(catId:"65264def2b0b88ce46cc9f64"){
    title
    refrenceImage
    stock_limite
    discount
    price
  }
}

# featureProductBrand ===>  featureProductBrand(brandId:"652642c2c196a4ec74554655")
{
  featureProductBrand(brandId:"652642c2c196a4ec74554655"){
    title
    iconUrl
    count
  }
}
# featureProductCategory ===>  featureProductCategory(catId:"6525a0feae5cfbbb9c0a2d93")
{
  featureProductCategory(catId:"6525a0feae5cfbbb9c0a2d93"){
    title
    iconUrl
    count
  }
}